name: danp04
title: How to build a Community of Tech Writers in your country following the example of Poland
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: danp04/feeling-responsive

color_scheme: new_color


aux_links:
  "Source repository on GitHub":
    - "//github.com/danp04/danp04.github.io/Test"

plugins:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate

paginate: 5                     
paginate_path: "blog/page:num"  

markdown           : kramdown
permalink          : /:categories/:title/
highlight          : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']

language: 'en'

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

defaults:
  -
    scope:
      path: ''
      type: "pages"
    values:
      show_meta: false 
      sidebar: right 
      comments: false

  -
    scope:
      path: ''
      type: "posts"
    values:
      show_meta: true
      sidebar: right
      comments: false

disqus_shortname: feelingresponsive

sass:
    sass_dir : _sass
    style    : :compressed


back_to_top: "true"
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the reference materials for the Technical Communication course at Vistula University (Warsaw)"