name: danp04
title: How to build a Community of Tech Writers in your country following the example of Poland
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: danp04/feeling-responsive

color_scheme: new_color


aux_links:
  "Source repository on GitHub":
    - "//github.com/danp04/danp04.github.io/Test"

back_to_top: "true"
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the reference materials for the Technical Communication course at Vistula University (Warsaw)"