
title: How to build a Community of Tech Writers in your country following the example of Poland
slogan: 'A Flexible Theme for Jekyll'
description: This Guide provides step-by-step instruction on developing and maintaining the community of practice. Such 
a community of practice in Poland has been formed successfully over the years and the demand for Documentation Specialists is constantly increasing.
remote_theme: danp04/test
aux_links: 
  "Source repository on Github":
  - "//github.com/danp04/test


